### ISSUE TITLE
Setup gulp based build system

### ISSUE THREAD

**Issue by mesprague** [learn-to-code-denver/learncoderate#8]
Resulting build system should compile template languages to finalized html, js, and css using an intermediary directory. Build system should also be capable of compiling documentation and running tests

**Comment by mesprague** [comment]
Are we still planning to use gulp?

**Comment by ab7** [comment]
@mesprague - I think we should definitely setup a build pipeline for front end assets. I think the repo merger wiped some files out, including a gulpfile. My vote would be to add it back in.

**Comment by mesprague** [comment]
@ab7 Should I just add a simple boilerplate file to be filled in later?

**Comment by ab7** [comment]
That would be great @mesprague! We can create separate issues to add gulp tasks.

**Comment by mesprague** [comment]
Gulp skeleton is implemented. Individual build tasks will be separate issues.
